"""add roles

Revision ID: aaecd817083b
Revises: 25b21738fb57
Create Date: 2024-04-14 16:20:16.487712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaecd817083b'
down_revision = '25b21738fb57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_roles_key'), 'roles', ['key'], unique=False)
    op.create_table('users_roles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('role_key', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_key'], ['roles.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_index(op.f('ix_roles_key'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
